const devotionals = {
  A: { title: "Almighty", definition: "God is all-powerful, sovereign over all creation.", scripture: "Genesis 17:1" },
  B: { title: "Bread of Life", definition: "Jesus sustains our souls just as bread sustains our bodies.", scripture: "John 6:35" },
  C: { title: "Counselor", definition: "God gives wisdom and guidance to those who seek Him.", scripture: "Isaiah 9:6" },
  D: { title: "Deliverer", definition: "The Lord rescues His people from danger and sin.", scripture: "Psalm 18:2" },
  E: { title: "Everlasting", definition: "God has no beginning or end; He is eternal.", scripture: "Isaiah 40:28" },
  F: { title: "Faithful", definition: "God always keeps His promises and never fails.", scripture: "Deuteronomy 7:9" },
  G: { title: "Good Shepherd", definition: "Jesus cares for His flock and lays down His life for them.", scripture: "John 10:11" },
  H: { title: "Holy", definition: "God is perfectly pure, set apart, and without sin.", scripture: "Isaiah 6:3" },
  I: { title: "Immanuel", definition: "God with us, revealed in the person of Jesus Christ.", scripture: "Matthew 1:23" },
  J: { title: "Judge", definition: "God is righteous and just, rewarding good and punishing evil.", scripture: "Psalm 7:11" },
  K: { title: "King of Kings", definition: "God rules over all rulers and authorities.", scripture: "1 Timothy 6:15" },
  L: { title: "Light of the World", definition: "Jesus shines in the darkness and brings life.", scripture: "John 8:12" },
  M: { title: "Messiah", definition: "The promised Savior who redeems His people.", scripture: "John 4:25-26" },
  N: { title: "Name Above All Names", definition: "The Lord's name is holy and exalted above every other.", scripture: "Philippians 2:9" },
  O: { title: "Omega", definition: "God is the end and completion of all things.", scripture: "Revelation 22:13" },
  P: { title: "Prince of Peace", definition: "Jesus brings reconciliation between God and humanity.", scripture: "Isaiah 9:6" },
  Q: { title: "Quickening Spirit", definition: "The Spirit gives life to what was dead.", scripture: "1 Corinthians 15:45" },
  R: { title: "Redeemer", definition: "The Lord rescues and restores His people from sin and bondage.", scripture: "Job 19:25" },
  S: { title: "Shepherd", definition: "The Lord provides, guides, and protects His people.", scripture: "Psalm 23:1" },
  T: { title: "Truth", definition: "God's Word and character are the absolute standard of truth.", scripture: "John 14:6" },
  U: { title: "Unchanging", definition: "God is the same yesterday, today, and forever.", scripture: "Hebrews 13:8" },
  V: { title: "Vine", definition: "Jesus is the source of life and fruitfulness for His people.", scripture: "John 15:5" },
  W: { title: "Way", definition: "Jesus is the only way to the Father.", scripture: "John 14:6" },
  X: { title: "eXalted One", definition: "The Lord is lifted high above all nations and peoples.", scripture: "Psalm 46:10" },
  Y: { title: "Yahweh", definition: "The covenant name of God, 'I AM WHO I AM.'", scripture: "Exodus 3:14" },
  Z: { title: "Zealous", definition: "The Lord is passionate for His people and His glory.", scripture: "Isaiah 42:13" }
};
